# Generated by Django 5.2.5 on 2025-09-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_capacity_car_location_car_owner_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owner_phone',
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(choices=[('tbilisi', 'Tbilisi'), ('batumi', 'Batumi'), ('kutaisi', 'Kutaisi'), ('rustavi', 'Rustavi'), ('gori', 'Gori'), ('zugdidi', 'Zugdidi'), ('poti', 'Poti'), ('telavi', 'Telavi'), ('mestia', 'Mestia')], default='tbilisi', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('tiptronic', 'Tiptronic')], default='automatic', max_length=20),
        ),
    ]
