# Generated by Django 5.2.5 on 2025-09-19 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='additional_features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='car',
            name='convenience',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='car',
            name='device_connectivity',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='car',
            name='vehicle_features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(),
        ),
    ]
