# Generated by Django 5.2.5 on 2025-09-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='capacity',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(choices=[('tbilisi', 'თბილისი'), ('batumi', 'ბათუმი'), ('kutaisi', 'ქუთაისი'), ('rustavi', 'რუსთავი'), ('gori', 'გორი'), ('zugdidi', 'ზუგდიდი'), ('poti', 'ფოთი'), ('telavi', 'თელავი'), ('mestia', 'მესტია')], default='tbilisi', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='owner_phone',
            field=models.CharField(default='000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'ავტომატიკა'), ('manual', 'მექანიკა'), ('tiptronic', 'ტიპტრონიკი')], default='automatic', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
