# Generated by Django 5.2.5 on 2025-09-17 08:00

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_owner_phone_alter_car_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
