# Generated by Django 5.2.5 on 2025-09-21 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_additional_features_car_convenience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='pickup_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
